### ISSUE TITLE
Port support for M-Type twists

### ISSUE THREAD

**Issue by drbild** [milagro-crypto/milagro-crypto-c#218]
The `milagro-crypto/amcl` library recently added support for M-Type twists:
https://github.com/milagro-crypto/amcl/commit/6d6acbd0b767cb4f0dff5909b439adb9140134f2

Would it be possible to get those ported here to `milagro-crypto-c`?  This library uses a modern build system that is much easier to work with.

**Comment by kealan** [comment]
Hi We appreciate your two contributions. Our plan, in the early new year, is to sync this repo with AMCL.  So at this stage we are not going to accept your PR.

**Comment by drbild** [comment]
Makes sense, thanks.  Looking forward to the sync!

**Comment by kealan** [comment]
Hi We have released V 4.3 which has support for M-Type twists

**Comment by drbild** [comment]
Thank you!
