### ISSUE TITLE
Headers in a sub-directory

### ISSUE THREAD

**Issue by zanebeckwith** [milagro-crypto/milagro-crypto-c#226]
Is there interest in putting the headers under a sub-directory, for example `amcl` or something, so that when you install them they go under, for example, `/usr/include/amcl` rather than directly in `/usr/include` (or wherever the system include path is on the system)?

Generically-named headers like `utils.h` are problematic when installed directly.

**Comment by kealan** [comment]
Hi You just need to set 
 -D CMAKE_INSTALL_PREFIX=...
when you are building the code

**Comment by drbild** [comment]
No, that changes the install *prefix*.  #244 adds support for a *suffix*.
