### ISSUE TITLE
print_out function name in tests conflicts

### ISSUE THREAD

**Issue by jaromil** [milagro-crypto/milagro-crypto-c#252]
https://github.com/milagro-crypto/milagro-crypto-c/blob/fe3a87505bc7c2039805fdeeec86785daaf4ac26/test/test_rsa_sign_WWW_ZZZ.c#L198

beware this function name prevents succesfull builds, yelding to:
```
[ 32%] Linking C executable test_rsa_sign_4096_NIST256
../lib/libamcl_x509.a(x509.c.o): In function `print_out':
x509.c:(.text+0x12f0): multiple definition of `print_out'
CMakeFiles/test_rsa_sign_4096_NIST256.dir/test_rsa_sign_4096_NIST256.c.o:test_rsa_sign_4096_NIST256.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```
should be trivial to fix...

**Comment by kealan** [comment]
Hi Thanks for that. That should be fixed in develop and I am making a PR to master now.
