### ISSUE TITLE
AES_GCM de/crypt with curve BLS383

### ISSUE THREAD

**Issue by jaromil** [milagro-crypto/milagro-crypto-c#285]
dear Milagro devs, experimenting with ECDH and in particular AES_GCM de/cryption (pbc_support.c) for curve BLS383 I've stumbled into a segfault which may signal a bug.

I believe it is reproducible by creating two pub/priv keyrings with BLS383 then computing a  session key for them using `ECP_BLS383_SVDP_DH`. Then using this session key as `K` argument into `AES_GCM_ENCRYPT(k, iv, h, in, out, t)` it segfaults inside that function.

I am reasonably sure of my code here, since the very same procedure using curve ED25519 leads to success and all my tests pass.

Do you have any insights? are AES_GCM operations on BLS383 supported in milagro and covered by tests?

thanks!

**Comment by mcarrickscott** [comment]
Hello Jaromil,


The raw output from ECP_BLS383_SVDP_DH is not quite ready to be used
directly as an AES key, and should not be so used.

First it should be passed through a Key Derivation Function, like KDF2
(from ecdh_support.c), which also creates a key of the appropriate size for
use with the AES.

For example the raw output from  ECP_BLS383_SVDP_DH is 384 bits. The
appropriate security level for using AES with this curve would be 192-bits
(and the max AES key size is 256 bits), which may explain the seg fault.

I guess using AES_GCM with a curve like BLS383 is not something we had
considered. But obviously its something that should be doable.

Making a copy of KDF2 inside of pbc_support.c might be the best way
forward...


Mike

**Comment by jaromil** [comment]
dear Mike, many thanks for your clear answer! using KDF2 should do.

I have one more question which is slightly related: is the BLS383 the same curve named "M-383" by DJB in https://safecurves.cr.yp.to ? I'm using BLS383 since it seems the only "safe" curve in that list which has also ECP2 and pairing functionalities implemented in Milagro.

**Comment by mcarrickscott** [comment]
Hello Jaromil,

No its not the same curve. Curve M-383 is Montgomery curve and is not
pairing-friendly. The only commonality with our BLS383 curve is that it
targets the same level of security.

M-383 was proposed for regular ECC use here https://eprint.iacr.org/2013/647

BLS383 is our own proposal, and is not covered by the safecurves list.

Mike

**Comment by jaromil** [comment]
Thanks again Mike, all clear!
