### ISSUE TITLE
make doc  fails on ubuntu 16.04

### ISSUE THREAD

**Issue by cjpn** [milagro-crypto/milagro-crypto-c#296]
I have just built and tested the library, all tests passed. When trying to make the documentation using make doc
I got the following error:

Building file list...
/opt/milagro-crypto-c/target/build/include/wcc192_BLS24.h:21: error: the name `wcc_BLS24.h' supplied as the second argument in the \file statement is not an input file (warning treated as error, aborting now)
Exiting...

The file referred to (wcc_BLS24.h) is not in the include directory. I have not used cmake, or doxygen before so I am not sure where to start tracking this down.

**Comment by samueleAndreoli** [comment]
Hi cjpn,
that's a bug with the documentation for the new BLS24 and BLS48 curves. Thanks for pointing that out.
I'm fixing that right now
