### ISSUE TITLE
Includes should be namespaced

### ISSUE THREAD

**Issue by elv-peter** [milagro-crypto/milagro-crypto-c#301]
Instead of installing includes in <dist>/include/, they should be put in a directory like <dist>/include/amcl. And in the source code, use "#include "amcl/arch.h".

The current way causes problems when there are headers with the same name. My build is breaking because it picks up the milagro utils.h instead of the dependent project's utils.h (which should also be namespaced, but it doesn't excuse milagro)

**Comment by drbild** [comment]
The `AMCL_INCLUDE_SUBDIR` CMake option was added as a temporary workaround for this.

For example,
```
cd build
cmake .. -DAMCL_INCLUDE_SUBDIR=amcl
make
make install
```
will install the headers to `/usr/include/amcl/*.h`.

Of course, this should be made the default structure.

**Comment by kealan** [comment]
I am happy to remove AMCL_INCLUDE_SUBDIR and make the build do the right thing by default. It will break a few project builds but is probably a better long term solution? What do you think?

**Comment by drbild** [comment]
+1 from me.  That is definitely a better long-term solution.

**Comment by jaromil** [comment]
+1 while wondering who uses an installed version of milagro for building? the main usecase is static compilation I guess.

**Comment by drbild** [comment]
We use installed versions here at [Xaptum](https://www.xaptum.com). Several pieces of our software are shipped as system packages (e.g., `deb`s on Debian) and use AMCL.  So we ship AMCL as a shared system library.

Obviously for smaller embedded systems, we compile it statically.

**Comment by elv-peter** [comment]
@jaromil We use CMake with a shared "install" directory for project dependencies, i.e. we do not install system-wide, instead it's more like a build output directory specified by CMAKE_INSTALL_PREFIX
